{
    'name': 'MML Base Platform',
    'version': '19.0.1.0.0',
    'summary': 'Event bus, capability registry, service locator, and billing ledger for MML modules',
    'author': 'MML Consumer Products Ltd',
    'website': 'https://www.mmlconsumerproducts.co.nz',
    'category': 'Technical',
    'license': 'LGPL-3',
    'depends': ['mail', 'base'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_cron.xml',
        'views/mml_event_dispatch_failure_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'installable': True,
    'auto_install': False,
    'application': False,
}
