{
    'name': 'MML Barcode Registry',
    'version': '19.0.1.0.0',
    'category': 'Inventory',
    'summary': 'GTIN lifecycle management and one-click allocation',
    'author': 'MML Consumer Products',
    'license': 'OPL-1',
    'depends': [
        'mml_base',
        'stock',
        'product',
        'mail',
    ],
    'data': [
        'security/barcode_registry_security.xml',
        'security/ir.model.access.csv',
        'data/barcode_prefix_data.xml',
        'views/mml_brand_views.xml',
        'views/barcode_prefix_views.xml',
        'views/barcode_registry_views.xml',
        'views/barcode_allocation_views.xml',
        'views/product_views.xml',
        'views/dashboard_views.xml',
        'views/menu.xml',
        'wizard/wizard_views.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'installable': True,
    'auto_install': False,
    'application': True,
    'web_icon': 'mml_barcode_registry,static/description/icon.png',
}
